### ISSUE TITLE
General Discussion about Ontology

### ISSUE THREAD

**Issue by l00mi** [tcfassociation/renamed-old-repo#1]
Please start here if you have any questions regarding the Ontology Management with tcftest.org.

**Comment by l00mi** [comment]
Where can I participate to this forum?

**Comment by l00mi** [comment]
Currently you can only participate through https://github.com/tcfassocation/ontology/issues/1 . This will change in the next iteration.

**Comment by ktk** [comment]
@l00mi ok thanks, will continue to ask questions in here

**Comment by ktk** [comment]
My todo list:

* show something fancy
* show something even more fancy

**Comment by l00mi** [comment]
Current state on the interface tcftest.org.
**Bold** _Italic_

**Comment by wombattaylor** [comment]
test comment

**Comment by wombattaylor** [comment]
other test comment

**Comment by l00mi** [comment]
Test

**Comment by l00mi** [comment]
Short test.

**Comment by l00mi** [comment]
test

**Comment by wombattaylor** [comment]
wombat test

**Comment by l00mi** [comment]
@wombattaylor did you use tcftest.org ?

**Comment by wombattaylor** [comment]
@l00mi with developer tools and disabled cache. comment shows up immediately.

**Comment by wombattaylor** [comment]
comment with direct fetch call

**Comment by wombattaylor** [comment]
other direct fetch call comment

**Comment by wombattaylor** [comment]
and again a direct fetch call comment

**Comment by l00mi** [comment]
comment with last

**Comment by wombattaylor** [comment]
New comment 19th feb

**Comment by niclasolofsson1** [comment]
Test
